### ISSUE TITLE
Missing? Performance test `item.owl`

### ISSUE THREAD

**Issue by Ptival** [ge-semtk/semtk#19]
Trying to run the performance tests, but `item.owl` seems nowhere to be found.

**Comment by Ptival** [comment]
cf. https://github.com/ge-semtk/semtk/blob/15d8ba64d2e9138c0565f5488def25e93b0acafe/standaloneExecutables/src/main/java/com/ge/research/semtk/standaloneExecutables/PerformanceTest.java#L342

**Comment by cuddihyge** [comment]
I see capitalized Item.owl in src/main/resources

**Comment by cuddihyge** [comment]
I also see that I was cheating and specifying sparqlGraphLibrary/src/test/resources for some files.    So make sure you have a local copy and that parameter is correct.
Otherwise it may just be the difference between case-sensitive and non-case-sensitive file systems

**Comment by cuddihyge** [comment]
I've also noticed that this performance test does not determine the optimal number of threads.  That is done in the ingestion rest service.  So if we care about that, we'll have to use DataLoader.overrideMaxThreads(0)

**Comment by Ptival** [comment]
Indeed I'm on a case-sensitive file system and did a case-sensitive file search! :-) Thanks!
