### ISSUE TITLE
License headers

### ISSUE THREAD

**Issue by udp** [ge-semtk/semtk#2]
Hi,

The license file in this repository says the code is licensed under Apache 2.0.  However, some files seem to have a different license header, e.g. https://github.com/ge-semtk/semtk/blob/ecc5bcdc56210b7c73cd71de373e5bea29a166c0/sparqlGraphWeb/iidx-oss/components/oo-utils/src/js/oo-utils.js.

    /*
     * Copyright (c) 2013 GE Global Research. All rights reserved.
     *
     * The copyright to the computer software herein is the property of
     * GE Global Research. The software may be used and/or copied only
     * with the written permission of GE Global Research or in accordance
     * with the terms and conditions stipulated in the agreement/contract
     * under which the software has been supplied.
     */

Are these files also included under the Apache license?  If so, should the source file headers be updated?

**Comment by ge-semtk** [comment]
I think "or in accordance with the terms and conditions stipulated in the agreement/contract under which the software has been supplied" does the trick.
The software has been supplied under Apache 2.0.
